=== nemetviiktor/N95LGIMDbGyak/03.02/NVI_XML_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- Felepitas -->
    <xs:element name="N95LGI">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="etterem" type="etterem_tipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="foszakacs" type="foszakacs_tipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="szakacs" type="szakacs_tipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="gyakornok" type="gyakornok_tipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="vendeg" type="vendeg_tipus" maxOccurs="unbounded"></xs:element>
                <xs:element name="rendeles" type="rendeles_tipus" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
        
        <!-- Elsődleges kulcsok -->
        <xs:key name="etterem_kulcs">
            <xs:selector xpath="etterem"></xs:selector>
            <xs:field xpath="@ekod"></xs:field>
        </xs:key>
        
        <xs:key name="foszakacs_kulcs">
            <xs:selector xpath="foszakacs"></xs:selector>
            <xs:field xpath="@fkod"></xs:field>
        </xs:key>
        
        <xs:key name="szakacs_kulcs">
            <xs:selector xpath="szakacs"></xs:selector>
            <xs:field xpath="@szkod"></xs:field>
        </xs:key>
        
        <xs:key name="gyakornok_kulcs">
            <xs:selector xpath="gyakornok"></xs:selector>
            <xs:field xpath="@gykod"></xs:field>
        </xs:key>
        
        <xs:key name="vendeg_kulcs">
            <xs:selector xpath="vendeg"></xs:selector>
            <xs:field xpath="@vkod"></xs:field>
        </xs:key>
        
        <!-- Idegen kulcsok -->
        <xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs">
            <xs:selector xpath="rendeles"></xs:selector>
            <xs:field xpath="@e_v_e"></xs:field>
        </xs:keyref>
        
        <xs:keyref refer="vendeg_kulcs" name="vendeg_idegen_kulcs">
            <xs:selector xpath="rendeles"></xs:selector>
            <xs:field xpath="@e_v_v"></xs:field>
        </xs:keyref>
        
        <xs:keyref refer="etterem_kulcs" name="etterem_foszakacs_idegen_kulcs">
            <xs:selector xpath="foszakacs"></xs:selector>
            <xs:field xpath="@e_f"></xs:field>
        </xs:keyref>
        
        <xs:keyref refer="etterem_kulcs" name="etterem_szakacs_idegen_kulcs">
            <xs:selector xpath="szakacs"></xs:selector>
            <xs:field xpath="@e_sz"></xs:field>
        </xs:keyref>
        
        <xs:keyref refer="etterem_kulcs" name="etterem_gyakornok_idegen_kulcs">
            <xs:selector xpath="gyakornok"></xs:selector>
            <xs:field xpath="@e_gy"></xs:field>
        </xs:keyref>
        
        <!-- Az 1:1 kapcsolat megvalósítás -->
        <xs:unique name="uniqe_foszakacs">
            <xs:selector xpath="foszakacs"></xs:selector>
            <xs:field xpath="@e_f"></xs:field>
        </xs:unique>
    </xs:element>
    
    <!-- Tipusok -->
    <xs:complexType name="etterem_tipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"></xs:element>
            <xs:element name="cim" type="cim_tipus"></xs:element>
            <xs:element name="csillag" type="xs:integer"></xs:element>
        </xs:sequence>
        <xs:attribute name="ekod" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="cim_tipus">
        <xs:sequence>
            <xs:element name="varos" type="xs:string"></xs:element>
            <xs:element name="utca" type="xs:string"></xs:element>
            <xs:element name="hazszam" type="xs:integer"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="foszakacs_tipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"></xs:element>
            <xs:element name="eletkor" type="xs:integer"></xs:element>
            <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
        <xs:attribute name="fkod" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="e_f" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="szakacs_tipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"></xs:element>
            <xs:element name="reszleg" type="xs:string"></xs:element>
            <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
        <xs:attribute name="szkod" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="e_sz" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="gyakornok_tipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"></xs:element>
            <xs:element name="gyakorlat" type="gyakorlat_tipus"></xs:element>
            <xs:element name="muszak" type="xs:string" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
        <xs:attribute name="gykod" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="e_gy" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="gyakorlat_tipus">
        <xs:sequence>
            <xs:element name="kezdete"></xs:element>
            <xs:element name="idotartama"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="vendeg_tipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"></xs:element>
            <xs:element name="eletkor" type="xs:integer"></xs:element>
            <xs:element name="cim" type="cim_tipus"></xs:element>
        </xs:sequence>
        <xs:attribute name="vkod" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="rendeles_tipus">
        <xs:sequence>
            <xs:element name="osszeg" type="xs:integer"></xs:element>
            <xs:element name="etel" type="xs:string"></xs:element>
        </xs:sequence>
        <xs:attribute name="e_v_e" type="xs:string" use="required"></xs:attribute>
        <xs:attribute name="e_v_v" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== nemetviiktor/N95LGIMDbGyak/03.02/NVI_XML.xml
<?xml version="1.0" encoding="UTF-8"?>

<N95LGI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NVI_XML_Schema.xsd">
    <!-- Ettermek -->
    <etterem ekod="e1">
        <nev>Trófea</nev>
        <cim>
            <varos>Budapest</varos>
            <utca>Visegrádi</utca>
            <hazszam>13</hazszam>
        </cim>
        <csillag>4</csillag>
    </etterem>
    
    <etterem ekod="e2">
        <nev>Gundel</nev>
        <cim>
            <varos>Budapest</varos>
            <utca>Gundel Károly</utca>
            <hazszam>4</hazszam>
        </cim>
        <csillag>5</csillag>
    </etterem>
    
    <!-- Foszakacsok -->
    <foszakacs fkod="f1" e_f="e1">
        <nev></nev>
        <eletkor>23</eletkor>
        <vegzettseg></vegzettseg>
        <vegzettseg></vegzettseg>
    </foszakacs>
    
    <foszakacs fkod="f2" e_f="e2">
        <nev></nev>
        <eletkor>23</eletkor>
        <vegzettseg></vegzettseg>
    </foszakacs>
    
    <!-- Szakacsok -->
    <szakacs szkod="sz1" e_sz="e1">
        <nev></nev>
        <reszleg></reszleg>
        <vegzettseg></vegzettseg>
        <vegzettseg></vegzettseg>
        <vegzettseg></vegzettseg>
    </szakacs>
    
    <szakacs szkod="sz2" e_sz="e1">
        <nev></nev>
        <reszleg></reszleg>
        <vegzettseg></vegzettseg>
        <vegzettseg></vegzettseg>
        <vegzettseg></vegzettseg>
    </szakacs>
    
    <szakacs szkod="sz3" e_sz="e2">
        <nev></nev>
        <reszleg></reszleg>
        <vegzettseg></vegzettseg>
        <vegzettseg></vegzettseg>
        <vegzettseg></vegzettseg>
    </szakacs>
    
    <szakacs szkod="sz4" e_sz="e2">
        <nev></nev>
        <reszleg></reszleg>
        <vegzettseg></vegzettseg>
        <vegzettseg></vegzettseg>
        <vegzettseg></vegzettseg>
    </szakacs>
    
    <!-- Gyakornokok -->
    <gyakornok gykod="gy1" e_gy="e1">
        <nev></nev>
        <gyakorlat>
            <kezdete></kezdete>
            <idotartama></idotartama>
        </gyakorlat>
        <muszak></muszak>
    </gyakornok>
    
    <gyakornok gykod="gy2" e_gy="e2">
        <nev></nev>
        <gyakorlat>
            <kezdete></kezdete>
            <idotartama></idotartama>
        </gyakorlat>
        <muszak></muszak>
    </gyakornok>
    
    <!-- Vendegek -->
    <vendeg vkod="v1">
        <nev>Német Viktor</nev>
        <eletkor>23</eletkor>
        <cim>
            <varos>Miskolc</varos>
            <utca>Kossuth Lajos</utca>
            <hazszam>44</hazszam>
        </cim>
    </vendeg>
    
    <vendeg vkod="v2">
        <nev>Ujlaki Róbert</nev>
        <eletkor>23</eletkor>
        <cim>
            <varos>Budapest</varos>
            <utca>Váci</utca>
            <hazszam>1</hazszam>
        </cim>
    </vendeg>
    
    <!-- Rendelesek -->
    <rendeles e_v_e="e1" e_v_v="v1">
        <osszeg>9000</osszeg>
        <etel>Steak</etel>
    </rendeles>
    
    <rendeles e_v_e="e1" e_v_v="v2">
        <osszeg>2500</osszeg>
        <etel>Leves</etel>
    </rendeles>
    
    <rendeles e_v_e="e2" e_v_v="v1">
        <osszeg>3500</osszeg>
        <etel>Mákos guba</etel>
    </rendeles>
    
    <rendeles e_v_e="e2" e_v_v="v2">
        <osszeg>3600</osszeg>
        <etel>Tészta</etel>
    </rendeles>
</N95LGI>
